# Generated by Django 3.0.7 on 2020-06-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nationnalite', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Joeur',
                'verbose_name_plural': 'Joeurs',
            },
        ),
    ]
