# Generated by Django 3.0.7 on 2020-06-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joueur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joueur',
            options={'verbose_name': 'Joueur', 'verbose_name_plural': 'Joueurs'},
        ),
        migrations.AddField(
            model_name='joueur',
            name='maillot',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
