# Generated by Django 3.0.7 on 2020-06-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joueur', '0002_auto_20200607_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='maillot',
            field=models.PositiveIntegerField(max_length=2),
        ),
    ]
