# Generated by Django 3.0.7 on 2020-06-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joueur', '0003_auto_20200607_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='maillot',
            field=models.PositiveIntegerField(),
        ),
    ]
