# Generated by Django 3.0.7 on 2020-06-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joueur', '0004_auto_20200607_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='masse',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joueur',
            name='taille',
            field=models.PositiveIntegerField(default=1.98),
            preserve_default=False,
        ),
    ]
