# Generated by Django 3.0.7 on 2020-06-07 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_auto_20200607_0122'),
        ('joueur', '0005_auto_20200607_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='equipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Equipe', to='equipe.Equipe'),
            preserve_default=False,
        ),
    ]
