# Generated by Django 3.0.7 on 2020-06-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joueur', '0006_auto_20200607_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/joueurs/'),
        ),
    ]
