# Generated by Django 3.0.7 on 2020-06-07 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joueur', '0006_joueur_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joueur',
            name='date_upd',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
