# Generated by Django 3.0.7 on 2020-06-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joueur', '0007_joueur_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joueur',
            name='equipe',
        ),
    ]
