# Generated by Django 3.0.7 on 2020-06-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joueur', '0008_remove_joueur_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/'),
        ),
    ]
