# Generated by Django 3.0.7 on 2020-06-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joueur', '0009_auto_20200608_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='joueur/photos/'),
        ),
    ]
