# Generated by Django 3.0.7 on 2020-06-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='coach',
            field=models.CharField(max_length=255),
        ),
    ]
