# Generated by Django 3.0.7 on 2020-06-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0004_equipe_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipe',
            options={'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipe'},
        ),
    ]
