# Generated by Django 3.0.7 on 2020-06-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0005_auto_20200607_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='equipe/logo/'),
        ),
    ]
