# Generated by Django 3.0.7 on 2020-06-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adversaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/images/aversaires-logo/')),
                ('nationnalite', models.CharField(max_length=255)),
                ('stade', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adversaire',
                'verbose_name_plural': 'Adversaires',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='has_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='our_score',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='them_score',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
