# Generated by Django 3.0.7 on 2020-06-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_auto_20200607_0224'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='equipes',
            field=models.ManyToManyField(to='equipe.Equipe'),
        ),
    ]
