# Generated by Django 3.0.7 on 2020-06-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200608_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='adversaire',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Adversaire', to='game.Adversaire'),
            preserve_default=False,
        ),
    ]
