# Generated by Django 3.0.7 on 2020-06-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_adversaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matchs'},
        ),
    ]
