# Generated by Django 3.0.7 on 2020-06-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200608_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adversaire',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='game/logo/'),
        ),
    ]
